function beginIteracao(nomes, funcao){
	$("#bash").append( funcao );
	var html = "";
	html += "<table class='iteracoes' border=1> <thead> <tr>";
	for (i = 0; i < nomes.length; i++){
		html += "<th>"+nomes[i]+"</th>";
	}
	html += "</tr> </thead> <tbody> <tr id='tbl_iteracao_next'> <td> <td> </tr> </tbody> </table>";
	$("#bash").append( html );
}

function makeIteracao( valores){
	var html = "<tr>";
	for (i = 0; i < valores.length; i++){
		html += "<td>"+valores[i]+"</td>";
	}
	html += "</tr>";
	$("#tbl_iteracao_next").replaceWith( html + "<tr id='tbl_iteracao_next'> <td> <td> </tr>" );
	
}
function endIteracao( ){
	$("#tbl_iteracao_next").replaceWith( "" );
	$("#bash").append( "<br />" );
}


function cosntruirEntradas(funcao){
	//~ transforma a assinatura da função em entradas
	//~ tá uma bagunça pq faz duas coisas complexas ao msm tempo
	var label, id, html, i = 0, virgula = "", args="";
	var func = "/* This was autogenerated, @see function cosntruirEntradas() */";
	
	var nome_div = funcao[i];
	i++;
	var div_id = funcao[i];
	i++;
	
	html = "<div class='entrada' id='"+div_id+"'></div>"
	$("#metodos").append(html);
	$("#" + div_id).append("<b class='nome_metodo'>"+nome_div+"</b>");
	
	for (; i < funcao.length; i++){
		label = id = funcao[i];
		
		html = "<br />\n<label for='"+div_id + id+"'>"+label+"</label>\n<input type='text' value='' id='"+div_id + id+"' size='2' />";
		
		$("#" + div_id).append(html);
		
		func += "var "+id+" = Number($('#"+div_id + id+"').val());";
		args += virgula+id;
		virgula = ",";
	}
	
	html = "<button id='btn_"+div_id+"'>"+div_id+"</button>";
	$("#" + div_id).append(html);
	
	func += "funcao_handdler.funcao = $('#funcao_alvo').val();";
	args += virgula + "funcao_handdler.funcao";
	func += "var val = "+div_id+"("+args+");";
	func += "if (val !== false){ $('#valor').text(val); } else { $('#valor').append( ' false' ); }";
	
	//~ @WARNIG se erro na linha abaixo, verificar o coódigo na var func
	//~ @LOG
	//~ $("#code").text(func);
	func = new Function( "x", func );
	
	$("#btn_"+div_id).click( func );
	/** protótipo maligno
			func += "var "+id+" = Number($('#"+div_id + id+"').val());";
			args += virgula+id;
			virgula = ",";
			args += virgula + "funcao_handdler.funcao";
			func += "var val = "+div_id+"("+args+");";
			func += "if (val !== false){ $('#valor').text(val); } else { $('#valor').append( ' false' ); }";
	*/
	
}

/*
 * raiz_gui.js
 * 
 * Copyright 2013 Luís Puhl <luispuhl@gmail.com>
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 * 
 * * Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above
 *   copyright notice, this list of conditions and the following disclaimer
 *   in the documentation and/or other materials provided with the
 *   distribution.
 * * Neither the name of the  nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * 
 */


